### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by bab1ch** [kobus-v-schoor/dotgit#31]
I'm unable to run `dotgit` since the last system update. I tried on fresh install also, no luck. I can't figure out where the issue is, did something changed in latest Python? 

```bash
dotgit update
Traceback (most recent call last):
  File "/home/bab1ch/.local/bin/dotgit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bab1ch/.local/share/pipx/venvs/dotgit/lib/python3.12/site-packages/dotgit/__main__.py", line 94, in main
    'encrypt': EncryptPlugin(
               ^^^^^^^^^^^^^^
  File "/home/bab1ch/.local/share/pipx/venvs/dotgit/lib/python3.12/site-packages/dotgit/plugins/encrypt.py", line 85, in __init__
    super().__init__(*args, data_dir=data_dir, **kwargs)
  File "/home/bab1ch/.local/share/pipx/venvs/dotgit/lib/python3.12/site-packages/dotgit/plugin.py", line 12, in __init__
    self.setup_data()
  File "/home/bab1ch/.local/share/pipx/venvs/dotgit/lib/python3.12/site-packages/dotgit/plugins/encrypt.py", line 91, in setup_data
    self.hashes = json.load(f)
                  ^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by bab1ch** [comment]
The hashes file has been corrupted. Here is the fix (replace the `dotgit` with your actual folder name in 2nd line)

```bash
#!/bin/bash
FILE="$HOME/dotgit/.plugins/encrypt/hashes"

# Create dir if missing
mkdir -p "$(dirname "$FILE")"

# If missing or invalid JSON, back it up and replace with {}
if ! [ -s "$FILE" ] || ! python -m json.tool "$FILE" >/dev/null 2>&1; then
  [ -f "$FILE" ] && cp -v "$FILE" "$FILE.bak.$(date +%s)"
  echo '{}' > "$FILE"
  echo "Repaired $FILE"
fi
```
